-- MySQL Script generated by MySQL Workbench
-- 03/04/15 20:42:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema c9
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `c9` ;

-- -----------------------------------------------------
-- Schema c9
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c9` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `c9` ;

-- -----------------------------------------------------
-- Table `c9`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c9`.`user` ;

CREATE TABLE IF NOT EXISTS `c9`.`user` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP  NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `address` VARCHAR(50) NULL,
  `phone` VARCHAR(10) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `type` TINYINT(1) NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `id_UNIQUE` (`iduser` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `c9`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c9`.`station` ;

CREATE TABLE IF NOT EXISTS `c9`.`station` (
  `idstation` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idstation`, `user_iduser`),
  INDEX `fk_station_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_station_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `c9`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `c9`.`gas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c9`.`gas` ;

CREATE TABLE IF NOT EXISTS `c9`.`gas` (
  `idgas` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgas`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `c9`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c9`.`order` ;

CREATE TABLE IF NOT EXISTS `c9`.`order` (
  `idorder` INT NOT NULL,
  `date` DATE NULL,
  `delivery` DATE NULL,
  `cost` FLOAT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idorder`, `user_iduser`),
  INDEX `fk_order_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `c9`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `c9`.`station_has_gas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c9`.`station_has_gas` ;

CREATE TABLE IF NOT EXISTS `c9`.`station_has_gas` (
  `station_idstation` INT NOT NULL,
  `gas_idgas` INT NOT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`station_idstation`, `gas_idgas`),
  INDEX `fk_station_has_gas_gas1_idx` (`gas_idgas` ASC),
  INDEX `fk_station_has_gas_station1_idx` (`station_idstation` ASC),
  CONSTRAINT `fk_station_has_gas_station1`
    FOREIGN KEY (`station_idstation`)
    REFERENCES `c9`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_station_has_gas_gas1`
    FOREIGN KEY (`gas_idgas`)
    REFERENCES `c9`.`gas` (`idgas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `c9`.`order_has_gas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c9`.`order_has_gas` ;

CREATE TABLE IF NOT EXISTS `c9`.`order_has_gas` (
  `order_idorder` INT NOT NULL,
  `gas_idgas` INT NOT NULL,
  `liters` INT NULL,
  PRIMARY KEY (`order_idorder`, `gas_idgas`),
  INDEX `fk_order_has_gas_gas1_idx` (`gas_idgas` ASC),
  INDEX `fk_order_has_gas_order1_idx` (`order_idorder` ASC),
  CONSTRAINT `fk_order_has_gas_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `c9`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_gas_gas1`
    FOREIGN KEY (`gas_idgas`)
    REFERENCES `c9`.`gas` (`idgas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
